In [197]:
## NAIVE BAYES CLASSIFIER
##IMPLEMENTATION USING DICTIONARY 


In [198]:
import numpy as np
import pandas as pd

In [199]:
class Naive_Bayes:
    def __init__(self):
        self.result={};
    
    
    def fit(self, X_train, Y_train):
        
        self.result={}
        class_values=set(Y_train)
        for current_class in class_values:
            self.result["total_data"]=len(Y_train)
            self.result[current_class]={}
            current_class_rows=(Y_train==current_class)
            Y_train_current=Y_train[current_class_rows]
            X_train_current=X_train[current_class_rows]
            self.result[current_class]["total_count"]=len(Y_train_current)
            num_features=X_train.shape[1]
            for j in range(1,num_features+1):
                self.result[current_class][j]={}
                all_possible_values=set(X_train[:,j-1])
                for current_value in all_possible_values:
                    self.result[current_class][j][current_value]=(X_train_current[:,j-1]==current_value).sum()
        
    
    
    
    
    def predict(self,X_test):
        Y_preds=[]
        
        for x in X_test:
            x_class=self.predictSinglePoint(x)
            Y_preds.append(x_class)
        return Y_preds
   
    
    def predictSinglePoint(self,x):
        classes= self.result.keys()
        best_class=-1
        best_class_probablity=-1000
        first_run=True
        for current_class in classes:
            if(current_class=="total_data"):
                continue
            p_current_class=self.probablity(x,current_class)
            
            if(first_run or p_current_class>best_class_probablity):
                best_class_probablity=p_current_class
                best_class=current_class
            first_run=False
        return best_class
    
    
    def probablity(self,x,current_class):
        output = np.log(self.result[current_class]["total_count"])-np.log(self.result["total_data"])
        num_features=len(self.result[current_class].keys())-1;
        for j in range(1,num_features+1):
            xj=x[j-1]
            count_current_class_with_value_xj=self.result[current_class][j][xj]+1
            count_current_class=self.result[current_class]["total_count"]+len(self.result[current_class][j].keys())
            current_xj_probablity=np.log(count_current_class_with_value_xj)-np.log(count_current_class)
            output=output+current_xj_probablity
        return output
    
    
    
    
    
    
    def marked_column(column):
        second_limit=column.mean()
        first_limit=0.5*column.mean()
        third_limit=1.5*column.mean()
        
        for i in range(0,len(column)):
            if(column[i]<first_limit):
                column[i]=1
            elif(column[i]<second_limit):
                column[i]=2
            elif(column[i]<third_limit):
                column[i]=3
            elif(column[i]>=third_limit):
                column[i]=4
        return column

In [200]:
from sklearn import datasets
iris= datasets.load_iris()
type(iris)
X=iris.data
Y=iris.target
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [201]:
for j in range(0,X.shape[1]):
    X[:,j]=Naive_Bayes.marked_column(X[:,j])


In [202]:
from sklearn import model_selection
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(X,Y,test_size=0.25,random_state=0)

In [203]:
nb=Naive_Bayes()
nb.fit(X_train,Y_train)

In [204]:
Y_predict=nb.predict(X_test)


In [205]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_test,Y_predict))
print(confusion_matrix(Y_test,Y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      1.00      0.97        16
           2       1.00      0.89      0.94         9

    accuracy                           0.97        38
   macro avg       0.98      0.96      0.97        38
weighted avg       0.98      0.97      0.97        38

[[13  0  0]
 [ 0 16  0]
 [ 0  1  8]]


In [ ]:
X=pd.DataFrame(X,columns=["Sepal_length","Sepal_width","Petal_length","Petal_width"])
Y=pd.DataFrame(Y,columns=["Target"])